name: Load Data and Run Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull tpawlak0322/lab4:1.0

    - name: Run Docker container
      run: |
        docker run -d -p 25565:25565 tpawlak0322/lab4:1.0

    - name: Wait for Flask to start (sleep 5 seconds)
      run: |
        sleep 5

    - name: Create data.json
      run: |
        echo '[
          {
            "rownames": 0,
            "gender": "male",
            "ethnicity": "other",
            "fcollege": "yes",
            "mcollege": "no",
            "home": "yes",
            "urban": "yes",
            "unemp": 6.2,
            "wage": 8.09,
            "distance": 0.2,
            "tuition": 0.88915,
            "education": 12,
            "income": "high",
            "region": "other"
          }
        ]' > data.json

    - name: Send POST request with data.json
      run: |
        curl -X POST -H "Content-Type: application/json" -d @data.json http://localhost:25565/predict

